USE `KANDIDATO_DB`;

-- drop tables
DROP TABLE IF EXISTS
`FLOWS`,
`VACANCIES`;

CREATE TABLE `FLOWS`
(
  FLOW_ID BIGINT(20) UNSIGNED NOT NULL AUTO_INCREMENT,
  PRIMARY KEY (FLOW_ID)
);

CREATE TABLE `VACANCIES`
(
  VACANCY_ID BIGINT(20) UNSIGNED NOT NULL AUTO_INCREMENT,
  PRIMARY KEY (VACANCY_ID)
);