USE `KANDIDATO`;

-- disable foreign keys
SET FOREIGN_KEY_CHECKS = 0;
-- drop tables
DROP TABLE IF EXISTS
`PEOPLE`,
`CONTACTS`,
`PEOPLE_TAGS`,
`TAGS`,
`FLOWS`,
`FLOW_ACTIONS`,
`USERS`,
`PROJECTS`,
`VACANCIES`,
`VACANCIES_TAGS`,
`RESUME`;


CREATE TABLE `PEOPLE` (
  PERSON_ID BIGINT(20) UNSIGNED NOT NULL AUTO_INCREMENT,
  FIRST_NAME VARCHAR(50) NOT NULL,
SECOND_NAME VARCHAR(50) NOT NULL,
  LAST_NAME VARCHAR(50) NOT NULL,
  CREATION_TIME DATETIME NOT NULL,
  PRIMARY KEY (PERSON_ID)
)  ENGINE=InnoDB;

CREATE TABLE `CONTACTS`
(
  CONTACT_ID   BIGINT(20) UNSIGNED NOT NULL AUTO_INCREMENT,
  CONTACT_TYPE VARCHAR(30)         NOT NULL,
  VALUE VARCHAR(30)         NOT NULL,
  PERSON_ID    BIGINT(20) UNSIGNED NOT NULL,
  PRIMARY KEY (CONTACT_ID),
  FOREIGN KEY `PEOPLE_FK` (PERSON_ID) REFERENCES PEOPLE (PERSON_ID)
    ON DELETE CASCADE
) ENGINE =InnoDB;

CREATE TABLE `TAGS` (
  TAG_ID BIGINT(20) UNSIGNED NOT NULL AUTO_INCREMENT,
  KEYWORD VARCHAR(30) NOT NULL,
  PRIMARY KEY (TAG_ID)
)  ENGINE=InnoDB;

CREATE TABLE `PEOPLE_TAGS` (
  TAG_ID BIGINT(20) UNSIGNED NOT NULL,
  PERSON_ID BIGINT(20) UNSIGNED NOT NULL,
  PRIMARY KEY (TAG_ID , PERSON_ID),
  INDEX (TAG_ID),
  FOREIGN KEY (TAG_ID)
  REFERENCES TAGS (TAG_ID)
    ON DELETE CASCADE,
  FOREIGN KEY (PERSON_ID)
  REFERENCES PEOPLE (PERSON_ID)
    ON DELETE CASCADE
)  ENGINE=InnoDB;

CREATE TABLE `FLOWS` (
  FLOW_ID BIGINT(20) UNSIGNED NOT NULL AUTO_INCREMENT,
  CREATION_TIME DATETIME NOT NULL,
  ACTIVE_FLAG BOOLEAN DEFAULT 1,
  VACANCY_ID BIGINT(20) UNSIGNED NOT NULL,
  flows_FLOW_ID BIGINT(20),
  PERSON_ID BIGINT(20) UNSIGNED NOT NULL,
  PRIMARY KEY (FLOW_ID),
  FOREIGN KEY (`VACANCY_ID`)
  REFERENCES `VACANCIES` (`VACANCY_ID`)
    ON DELETE CASCADE,
  FOREIGN KEY (`PERSON_ID`)
  REFERENCES `PEOPLE` (`PERSON_ID`)
    ON DELETE CASCADE
)  ENGINE=InnoDB;

CREATE TABLE `FLOW_ACTIONS` (
  FLOW_ACTION_ID BIGINT(20) UNSIGNED NOT NULL AUTO_INCREMENT,
  actions_FLOW_ACTION_ID BIGINT(20),
  CREATION_TIME DATETIME NOT NULL,
  FLOW_ID BIGINT(20) UNSIGNED NOT NULL,
  DESCRIPTION VARCHAR(16000),
  STATE VARCHAR(20) NOT NULL,
  PRIMARY KEY (FLOW_ACTION_ID),
  FOREIGN KEY (`FLOW_ID`)
  REFERENCES `FLOWS` (`FLOW_ID`)
    ON DELETE CASCADE
)  ENGINE=InnoDB;

CREATE TABLE `PROJECTS` (
  PROJECT_ID BIGINT(20) UNSIGNED NOT NULL AUTO_INCREMENT,
  CREATION_TIME DATETIME NOT NULL,
  NAME VARCHAR(50) NOT NULL,
  DESCRIPTION VARCHAR(16000),
  PRIMARY KEY (PROJECT_ID)
)  ENGINE=InnoDB;

CREATE TABLE `USERS` (
  USER_ID BIGINT(20) UNSIGNED NOT NULL AUTO_INCREMENT,
  PRIMARY KEY (USER_ID)
)  ENGINE=InnoDB;

CREATE TABLE `VACANCIES` (
  VACANCY_ID BIGINT(20) UNSIGNED NOT NULL AUTO_INCREMENT,
  CREATION_TIME DATETIME NOT NULL,
  HOT_FLAG BOOLEAN DEFAULT 1,
  DESCRIPTION VARCHAR(16000),
  STATE VARCHAR(20) NOT NULL,
  PROJECT_ID BIGINT(20) UNSIGNED NOT NULL,
  CREATOR_ID BIGINT(20) UNSIGNED NOT NULL,
  PRIMARY KEY (VACANCY_ID),
  FOREIGN KEY (PROJECT_ID)
  REFERENCES PROJECTS (PROJECT_ID)
    ON DELETE CASCADE,
  FOREIGN KEY (CREATOR_ID)
  REFERENCES USERS (USER_ID)
    ON DELETE CASCADE
)  ENGINE=InnoDB;

CREATE TABLE `VACANCIES_TAGS` (
  TAG_ID BIGINT(20) UNSIGNED NOT NULL,
  VACANCY_ID BIGINT(20) UNSIGNED NOT NULL,
  PRIMARY KEY (TAG_ID , VACANCY_ID),
  INDEX (TAG_ID),
  FOREIGN KEY (TAG_ID)
  REFERENCES TAGS (TAG_ID)
    ON DELETE CASCADE,
  FOREIGN KEY (VACANCY_ID)
  REFERENCES VACANCIES (VACANCY_ID)
    ON DELETE CASCADE
)  ENGINE=InnoDB;

CREATE TABLE `RESUME` (
  RESUME_ID BIGINT(20) UNSIGNED NOT NULL AUTO_INCREMENT,
  RESUME_DATA LONGBLOB NOT NULL,
  PRIMARY KEY (RESUME_ID)
)  ENGINE=InnoDB;

-- enabling foreign keys
SET FOREIGN_KEY_CHECKS = 1;