USE `KANDIDATO`;

CREATE TABLE `CUSTOMERS` (
  CUSTOMER_ID    BIGINT(20) UNSIGNED NOT NULL AUTO_INCREMENT,
  CREATION_TIME DATETIME            NOT NULL,
  NAME          VARCHAR(50)         NOT NULL,
  DESCRIPTION   VARCHAR(16000)
                CHARACTER SET utf8,
  PRIMARY KEY (CUSTOMER_ID)
)
  ENGINE =InnoDB;
commit; 
