USE `KANDIDATO`;

SET @ROWNUM = 0;
UPDATE USERS
SET
  LOGIN      = if(LOGIN = '', CONCAT('user', @ROWNUM:= @ROWNUM+1), LOGIN),
  PASSWORD   = if(PASSWORD = '', '$2a$10$StizF1/d1jQ4AV04FGUqg.eF.TdIj37pXzus4oJ67NdQ9Hj9oDa9K', PASSWORD),
  FIRST_NAME = if(FIRST_NAME = '', 'Name', FIRST_NAME),
  LAST_NAME  = if(LAST_NAME = '', 'Surname', LAST_NAME) ;

COMMIT;

ALTER TABLE `USERS`
ADD UNIQUE INDEX (LOGIN);