USE `KANDIDATO`;

-- disable foreign keys
SET FOREIGN_KEY_CHECKS = 0;
-- drop tables
DROP TABLE IF EXISTS
`CANDIDATES`,
`CONTACTS`,
`PEOPLE_TAGS`,
`TAGS`,
`FLOWS`,
`FLOW_ACTIONS`,
`USERS`,
`PROJECTS`,
`VACANCIES`,
`VACANCIES_TAGS`,
`RESUME`,
`COMMENTS`;


CREATE TABLE `CANDIDATES` (
  CANDIDATE_ID     BIGINT(20) UNSIGNED NOT NULL AUTO_INCREMENT,
  FIRST_NAME    VARCHAR(50)         NOT NULL,
  LAST_NAME     VARCHAR(50)         NOT NULL,
  CREATION_TIME DATETIME            NOT NULL,
  USER_ID BIGINT(20) UNSIGNED NOT NULL,
  FOREIGN KEY (USER_ID) REFERENCES USERS (USER_ID),
  PRIMARY KEY (CANDIDATE_ID)
)
  ENGINE =InnoDB;

CREATE TABLE `CONTACTS`
(
  CONTACT_ID   BIGINT(20) UNSIGNED NOT NULL AUTO_INCREMENT,
  CONTACT_TYPE VARCHAR(30)         NOT NULL,
  VALUE        VARCHAR(30)         NOT NULL,
  CANDIDATE_ID    BIGINT(20) UNSIGNED NOT NULL,
  PRIMARY KEY (CONTACT_ID),
  FOREIGN KEY `CANDIDATES_FK` (CANDIDATE_ID) REFERENCES CANDIDATES (CANDIDATE_ID)
    ON DELETE CASCADE
)
  ENGINE =InnoDB;

CREATE TABLE `TAGS` (
  TAG_ID  BIGINT(20) UNSIGNED NOT NULL AUTO_INCREMENT,
  KEYWORD VARCHAR(30)         NOT NULL,
  PRIMARY KEY (TAG_ID)
)
  ENGINE =InnoDB;

CREATE TABLE `CANDIDATE_TAGS` (
  TAG_ID    BIGINT(20) UNSIGNED NOT NULL,
  CANDIDATE_ID BIGINT(20) UNSIGNED NOT NULL,
  PRIMARY KEY (TAG_ID, CANDIDATE_ID),
  INDEX (TAG_ID),
  FOREIGN KEY (TAG_ID)
  REFERENCES TAGS (TAG_ID)
    ON DELETE CASCADE,
  FOREIGN KEY (CANDIDATE_ID)
  REFERENCES CANDIDATES (CANDIDATE_ID)
    ON DELETE CASCADE
)
  ENGINE =InnoDB;

CREATE TABLE `FLOWS` (
  FLOW_ID       BIGINT(20) UNSIGNED NOT NULL AUTO_INCREMENT,
  CREATION_TIME DATETIME            NOT NULL,
  ACTIVE_FLAG   BOOLEAN DEFAULT 1,
  VACANCY_ID    BIGINT(20) UNSIGNED NOT NULL,
  CANDIDATE_ID     BIGINT(20) UNSIGNED NOT NULL,
  USER_ID BIGINT(20) UNSIGNED NOT NULL,
  FOREIGN KEY (USER_ID) REFERENCES USERS (USER_ID),
  FOREIGN KEY (`VACANCY_ID`)
  REFERENCES `VACANCIES` (`VACANCY_ID`)
    ON DELETE CASCADE,
  FOREIGN KEY (`CANDIDATE_ID`)
  REFERENCES `CANDIDATES` (`CANDIDATE_ID`)
    ON DELETE CASCADE,
  PRIMARY KEY (FLOW_ID)
)
  ENGINE =InnoDB;

CREATE TABLE `FLOW_ACTIONS` (
  FLOW_ACTION_ID BIGINT(20) UNSIGNED NOT NULL AUTO_INCREMENT,
  CREATION_TIME  DATETIME            NOT NULL,
  FLOW_ID        BIGINT(20) UNSIGNED NOT NULL,
  DESCRIPTION    VARCHAR(16000)
                 CHARACTER SET utf8,
  STATE          VARCHAR(20)         NOT NULL,
  PRIMARY KEY (FLOW_ACTION_ID),
  FOREIGN KEY (`FLOW_ID`)
  REFERENCES `FLOWS` (`FLOW_ID`)
    ON DELETE CASCADE
)
  ENGINE =InnoDB;

CREATE TABLE `PROJECTS` (
  PROJECT_ID    BIGINT(20) UNSIGNED NOT NULL AUTO_INCREMENT,
  CREATION_TIME DATETIME            NOT NULL,
  NAME          VARCHAR(50)         NOT NULL,
  DESCRIPTION   VARCHAR(16000)
                CHARACTER SET utf8,
  USER_ID BIGINT(20) UNSIGNED NOT NULL,
  FOREIGN KEY (USER_ID) REFERENCES USERS (USER_ID),
  PRIMARY KEY (PROJECT_ID)
)
  ENGINE =InnoDB;

CREATE TABLE `USERS` (
  USER_ID BIGINT(20) UNSIGNED NOT NULL AUTO_INCREMENT,
  PRIMARY KEY (USER_ID)
)
  ENGINE =InnoDB;

CREATE TABLE `VACANCIES` (
  VACANCY_ID    BIGINT(20) UNSIGNED NOT NULL AUTO_INCREMENT,
  CREATION_TIME DATETIME            NOT NULL,
  HOT_FLAG      BOOLEAN DEFAULT 1,
  DESCRIPTION   VARCHAR(16000)
                CHARACTER SET utf8,
  STATE         VARCHAR(20)         NOT NULL,
  PROJECT_ID    BIGINT(20) UNSIGNED NOT NULL,
  USER_ID    BIGINT(20) UNSIGNED NOT NULL,
  PRIMARY KEY (VACANCY_ID),
  FOREIGN KEY (PROJECT_ID)
  REFERENCES PROJECTS (PROJECT_ID)
    ON DELETE CASCADE,
  FOREIGN KEY (USER_ID)
  REFERENCES USERS (USER_ID)
)
  ENGINE =InnoDB;

CREATE TABLE `VACANCIES_TAGS` (
  TAG_ID     BIGINT(20) UNSIGNED NOT NULL,
  VACANCY_ID BIGINT(20) UNSIGNED NOT NULL,
  PRIMARY KEY (TAG_ID, VACANCY_ID),
  INDEX (TAG_ID),
  FOREIGN KEY (TAG_ID)
  REFERENCES TAGS (TAG_ID)
    ON DELETE CASCADE,
  FOREIGN KEY (VACANCY_ID)
  REFERENCES VACANCIES (VACANCY_ID)
    ON DELETE CASCADE
)
  ENGINE =InnoDB;

CREATE TABLE `RESUME` (
  RESUME_ID BIGINT(20) UNSIGNED NOT NULL AUTO_INCREMENT,
  DATA LONGBLOB NOT NULL,
  STATE VARCHAR(20) NOT NULL,
  CANDIDATE_ID BIGINT(20) UNSIGNED NOT NULL,
  USER_ID BIGINT(20) UNSIGNED NOT NULL,
  FOREIGN KEY (CANDIDATE_ID) REFERENCES CANDIDATES (CANDIDATE_ID) ON DELETE CASCADE,
  FOREIGN KEY (USER_ID) REFERENCES USERS (USER_ID),
  PRIMARY KEY (RESUME_ID)
)
  ENGINE =InnoDB;

CREATE TABLE `COMMENTS`
(
  COMMENT_ID    BIGINT(20) UNSIGNED NOT NULL AUTO_INCREMENT,
  ENTITY_ID     BIGINT(20) UNSIGNED NOT NULL,
  USER_ID       BIGINT(20) UNSIGNED NOT NULL,
  CREATION_DATE DATETIME            NOT NULL,
  ENTITY_TYPE   VARCHAR(10),
  STATEMENT     VARCHAR(16000)
                CHARACTER SET utf8,
  PRIMARY KEY (COMMENT_ID),
  FOREIGN KEY (USER_ID)
  REFERENCES USERS (USER_ID)

)
  ENGINE =InnoDB;

-- enabling foreign keys
SET FOREIGN_KEY_CHECKS = 1;