INSERT INTO PROJECTS (`CREATION_TIME`,`NAME`, `DESCRIPTION`) VALUES(CURTIME(), "Test Project", "Project for Testing");

INSERT INTO USERS (`USER_ID`) VALUES(1);

INSERT INTO VACANCIES (`CREATION_TIME`, `HOT_FLAG`, `DESCRIPTION`, `STATE`, `PROJECT_ID`, `CREATOR_ID`) VALUES(CURTIME(), 0, "Java Spring JPA", "OPEN", 1, 1);