flyway.url=jdbc:mysql://web-kandidato.rhcloud.com:3306/
flyway.user=adminx9TfiCk
flyway.password=hC4t9-XZDlag
# Order of the schemas is important - versioning table will be created in the first schema listed
flyway.schemas=VERSION, KANDIDATO, QUARTZ
flyway.encoding=UTF-8
