flyway.url=jdbc:mysql://localhost:3306/
flyway.user=root
flyway.password=root
# Order of the schemas is important - versioning table will be created in the first schema listed
flyway.schemas=VERSION, KANDIDATO, QUARTZ
flyway.encoding=UTF-8
